#ifndef CRANE1_THEME_H
#define CRANE1_THEME_H
#include <QString>
// Visual theme shared with the current Basket Crane 1 design.
inline QString crane1Theme() { return QString(
		"QWidget {"
		"  color: #e2e8f0;"
		"  font-family: \"Segoe UI\";"
		"  font-size: 13px;"
		"}"
		"mainWindowClass, QDialog {"
		"  background-color: #0b1220;"
		"}"
		"#appHeader {"
		"  background-color: #111827;"
		"  border-bottom: 1px solid #263449;"
		"}"
		"#brandLogo {"
		"  color: #e11145;"
		"  font-size: 21px;"
		"  font-weight: 400;"
		"  background: transparent;"
		"}"
		"#applicationTitle {"
		"  color: #f8fafc;"
		"  font-size: 16px;"
		"  font-weight: 600;"
		"}"
		"#applicationSubtitle, #hostIdentity {"
		"  color: #94a3b8;"
		"  font-size: 11px;"
		"}"
		"#systemMode {"
		"  min-height: 22px;"
		"  padding: 2px 10px;"
		"  border-radius: 11px;"
		"  font-size: 11px;"
		"  font-weight: 700;"
		"}"
		"#systemMode[mode=\"live\"] {"
		"  color: #bbf7d0; background: #14532d; border: 1px solid #22c55e;"
		"}"
		"#systemMode[mode=\"test\"] {"
		"  color: #fde68a; background: #422006; border: 1px solid #d97706;"
		"}"
		"#systemMode[mode=\"observer\"] {"
		"  color: #dbeafe; background: #1e3a8a; border: 1px solid #60a5fa;"
		"}"
		"QGroupBox {"
		"  background-color: rgba(17, 24, 39, 232);"
		"  border: 1px solid #2d3b50;"
		"  border-radius: 8px;"
		"  margin-top: 14px;"
		"  padding: 10px 8px 8px 8px;"
		"  font-weight: 600;"
		"  color: #f8fafc;"
		"}"
		"QGroupBox::title {"
		"  subcontrol-origin: margin;"
		"  left: 10px;"
		"  padding: 0 5px;"
		"  background-color: #111827;"
		"  border-radius: 3px;"
		"  color: #7dd3fc;"
		"  font-size: 12px;"
		"}"
		"QCheckBox, QRadioButton {"
		"  spacing: 7px;"
		"  min-height: 20px;"
		"  padding-bottom: 1px;"
		"  color: #e2e8f0;"
		"  background: transparent;"
		"}"
		"QCheckBox:hover, QRadioButton:hover { color: #ffffff; }"
		"QCheckBox:disabled, QRadioButton:disabled { color: #64748b; }"
		"QCheckBox::indicator, QRadioButton::indicator {"
		"  width: 16px;"
		"  height: 16px;"
		"}"
		"QCheckBox::indicator {"
		"  border: 1px solid #64748b;"
		"  border-radius: 4px;"
		"  background: #1e293b;"
		"}"
		"QCheckBox::indicator:checked {"
		"  background: #0ea5e9;"
		"  border-color: #38bdf8;"
		"}"
		"QRadioButton::indicator {"
		"  border: 1px solid #64748b;"
		"  border-radius: 8px;"
		"  background: #1e293b;"
		"}"
		"QRadioButton::indicator:checked {"
		"  background: #0ea5e9;"
		"  border: 4px solid #dbeafe;"
		"}"
		"QPushButton, QToolButton {"
		"  min-height: 26px;"
		"  padding: 3px 12px;"
		"  color: #ffffff;"
		"  background-color: #334155;"
		"  border: 1px solid #475569;"
		"  border-radius: 6px;"
		"  font-weight: 600;"
		"}"
		"QPushButton:hover {"
		"  background-color: #475569;"
		"  border-color: #64748b;"
		"}"
		"QPushButton:pressed {"
		"  background-color: #1e293b;"
		"}"
		"QPushButton[accent=\"true\"] {"
		"  background-color: #0284c7;"
		"  border-color: #38bdf8;"
		"}"
		"QPushButton[accent=\"true\"]:hover {"
		"  background-color: #0369a1;"
		"}"
		"QPushButton[warning=\"true\"] {"
		"  color: #ffffff; background-color: #78350f; border-color: #b45309;"
		"}"
		"QPushButton[warning=\"true\"]:hover {"
		"  background-color: #92400e; border-color: #f59e0b;"
		"}"
		"QPushButton:disabled, QToolButton:disabled {"
		"  color: #ffffff; background-color: #1e293b; border-color: #334155;"
		"}"
		"QLineEdit, QSpinBox, QComboBox {"
		"  min-height: 26px;"
		"  padding: 2px 8px;"
		"  color: #f8fafc;"
		"  background-color: #1e293b;"
		"  border: 1px solid #475569;"
		"  border-radius: 5px;"
		"  selection-background-color: #0284c7;"
		"}"
		"QLineEdit:focus, QSpinBox:focus, QComboBox:focus {"
		"  border-color: #38bdf8;"
		"}"
		"QSpinBox {"
		"  padding-right: 20px;"
		"}"
		"QSpinBox::up-button, QSpinBox::down-button {"
		"  subcontrol-origin: border;"
		"  width: 18px;"
		"  background-color: #334155;"
		"  border-left: 1px solid #475569;"
		"}"
		"QSpinBox::up-button {"
		"  subcontrol-position: top right;"
		"  border-top-right-radius: 4px;"
		"}"
		"QSpinBox::down-button {"
		"  subcontrol-position: bottom right;"
		"  border-bottom-right-radius: 4px;"
		"}"
		"QTableView {"
		"  color: #e2e8f0;"
		"  background-color: #111827;"
		"  alternate-background-color: #1e293b;"
		"  gridline-color: #334155;"
		"  border: 1px solid #334155;"
		"  border-radius: 5px;"
		"  selection-background-color: #075985;"
		"}"
		"QHeaderView::section {"
		"  color: #cbd5e1;"
		"  background-color: #1e293b;"
		"  border: 0;"
		"  border-right: 1px solid #334155;"
		"  border-bottom: 1px solid #334155;"
		"  padding: 6px;"
		"  font-weight: 600;"
		"}"
		"QScrollBar:vertical {"
		"  width: 12px;"
		"  background: #0f172a;"
		"}"
		"QScrollBar::handle:vertical {"
		"  min-height: 24px;"
		"  background: #475569;"
		"  border-radius: 6px;"
		"}"
		"QToolTip {"
		"  color: #f8fafc;"
		"  background-color: #1e293b;"
		"  border: 1px solid #64748b;"
		"  padding: 5px;"
		"}"
); }
#endif
